### PR TITLE
Get strata

### PR DESCRIPTION
**Pull request by kellijohnson-NOAA**
I think that we should merge this into at least development if not master even though we are not at the final version of `PullSpp()`. We can always do more development once the table access is opened up as noted by Beth. I worry about the branch getting stale if we wait, also there is some other functionality here that I need for VASTWestCoast.

### CODE REVIEW

**Comment by kellijohnson-NOAA** [comment]
Do you want help with Travis checks here?

**Comment by chantelwetzel-noaa** [comment]
I agree. Thank you @kellijohnson-NOAA  for being on top of this.

**Comment by kellijohnson-NOAA** [comment]
Thanks @chantelwetzel-noaa ... should I create an issue about PullSpp so I don't forget about future development for the function?

**Comment by chantelwetzel-noaa** [comment]
That would be great.  Thanks

**Pull request merged**
